name: Test GrepVF Action

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger the test manually from the Actions tab
  pull_request:              # <--- ADD THIS BLOCK
     branches: [ "main" ]

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
      issues: write # Needed for action to post the PR comment
      pull-requests: write # Needed for action to post the PR comment
      
    steps:
      - name: Checkout code to scan
        uses: actions/checkout@v4

      # Here is where you test your action! 
      # It points directly to your repo and the 'main' branch
      - name: Run GrepVF Scanner
        uses: AgnivaSengupta/grepvf-action-test@main